PersonalDiary/Controllers/DiaryCommentController.cs
using Diary.Service;
using Diary.Service.Diary;
using Diary.Service.DiaryComment;
using PersonalDiary.Filter;
using PersonalDiary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tgnet.Linq;
using Tgnet.Web.Mvc;
namespace PersonalDiary.Controllers
{
    [CustomHandletErrorAttribute]
    [CheckLogin]
    public class DiaryCommentController : BaseController
    {
        //一个用户有多条评论，一篇日志有多条评论
        // GET: DiaryComment
        //评论
        //主页显示发布过的视图
        //用户是否登陆，登陆的用户可以评论
        public IDiaryCommentManager _DiaryCommentManager;
        public IDiaryManager _DiaryManager;
       public DiaryCommentController(IDiaryCommentManager diarycommentmanager, IDiaryManager diarymanager)
        {
            _DiaryManager = diarymanager;
            _DiaryCommentManager = diarycommentmanager;
        }
      
        public ActionResult Index(int diaryid)
        {
            //判断用户是否登陆、、
            //if(User==null)
            //{
            //    throw new Tgnet.Api.ExceptionWithErrorCode(Tgnet.Api.ErrorCode.未登录);
            //Comment是单条日志下的所有评论
            Comment model = new Comment();
            //获取该条日志的服务
            var diaryservice = _DiaryManager.GetDiaryService(diaryid);
            model.Diaryid = diaryid;
            model.content = diaryservice.Content;
            //日志的用户ID diaryservice.UserId;
            //受到评论的日志的用户名
            model.UserName = diaryservice.UserName;
            //判断当前登陆User的ID和该条评论的用户ID是否一致,一样的话可以进行删除该条评论操作
            model.Title = diaryservice.Title;
         
            model.commentList = diaryservice.DiaryComment.ToList().Select(p => new DiaryCommentModel
            {
                CommentContent = p.CContent,
                DiaryCommentId = p.CommentId,
                //UserID代表该条评论的用户ID
                UserId = p.UserId, DiaryId= diaryid,
                // 
                CanDel =User!=null? (int)User.ID == p.UserId:false,
            }).ToArray();
            return View(model);
           
        }
        [AllowAnonymous]
        public ActionResult Add(int diaryid)
        {
            IDiaryService diaryService= _DiaryManager.GetDiaryService(diaryid);
            UserDiaryModel userDiaryModel = new UserDiaryModel
            {
                Content = diaryService.Content,
                CreateTime = diaryService.CreateTime,
                Title = diaryService.Title,
                UserDiaryId = diaryService.DiaryId,
                UserName = diaryService.UserName,
                UserId = diaryService.UserId
            };
            ViewBag.DiaryId = diaryid;
            return View(userDiaryModel);
        }
        [HttpPost]
        public ActionResult Add([Bind(Include = "CommentContent,DiaryId")] DiaryCommentModel diaryCommentModel)
        {
            //获取DiaryService服务，构造函数内部验证是否有这条日志，
            var DiaryManager = _DiaryManager.GetDiaryService(diaryCommentModel.DiaryId);
            //调用AddComment方法,该条评论的userid设置为当前登陆用户
            DiaryManager.AddComment(diaryCommentModel.CommentContent, (int)User.ID);
            //
            return RedirectToAction("UserIndex", "Diary",new { userid=(int)User.ID});
        }
        
        public ActionResult Delete(int diarycommentid)
        {
            //权限判断
            //获取UserCommentService服务，实例化服务对象，调用内部构造函数验证用户权限
            var messagecomment = _DiaryCommentManager.GetUserCommentService(diarycommentid,(int)User.ID);
            //DeleteComment方法内部调用Diarycommment中的Delete方法
            messagecomment.DeleteComment();
            //int   PamUserId = messagediary.UserId;
            return RedirectToAction("UserIndex","Diary", new
            {
                userid = User.ID
            });
        }
    }
}

PersonalDiary/Controllers/DiaryController.cs
using Diary.Data;
using Diary.Service;
using Diary.Service.Diary;
using PersonalDiary.Filter;
using PersonalDiary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tgnet;
using Tgnet.Api;
using Tgnet.Linq;
using Tgnet.Web.Mvc;

namespace PersonalDiary.Controllers
{
    [CustomHandletErrorAttribute]
    [CheckLogin]
    public class DiaryController : BaseController
    {
        IDiaryManager _DiaryManager;
        IUserManager _userManager;
        public DiaryController(IDiaryManager DiaryManager, IUserManager userManager)
        {
            _DiaryManager = DiaryManager;
            _userManager = userManager;
        }
        // GET: Default
        //1.所有用户日志列表页面
        //2.当前用户日志列表
        [AllowAnonymous]
        public ActionResult UserIndex(int? userid=null , int value = 1, int page = 1, string searchInfo = null)
        {
            // 1. 从数据库中读取实体对象 (Diary)
            //var repository = new DiaryRepository(new DiariesEntities());
            //var diaries = repository.NoTackingDiary.ToList();
            //var Diary=_DiaryManager.NoTackingDiary;
            //// 2. 将实体对象转换成 Model
            //var diaries = Diary.Where(diary => diary.UserId == userid);
            //// 3. 将 Model 对象传递给视图 (View)
            //return View(diaries);
            //1.从Diary仓储类中找到UserId==userid的实体集 （IQueryable类型）
            
            var messagediary = _DiaryManager.NoTackingDiary;
            ViewBag.Select = value;
            ViewBag.searchInfo = searchInfo;
            //找到所有公开的日志
            if (User == null)
            {
                //公开的
                //ViewBag.userid=0代表用户未登录
                messagediary = messagediary.Where(d => d.IsPrivate == false);
                ViewBag.userid = 0;
            }
            //用户未登录的情况下ViewBag.userid=0
            //用户登录后
            //显示的是自己的所有日志和别人的公开日志
            if (User != null)
            {
                messagediary = messagediary.Where(d => (d.UserId == User.ID && d.IsPrivate == true) || d.IsPrivate == false);
                //把用户登录ID赋值ViewBag.userid
                ViewBag.userid = User.ID;
            }
            int pageSize = 10; int count; int pageCount;
            PageModel<UserDiaryModel> userDiaryModels = null;
            //根据value排序
            if (value == 1)
            {
                ViewBag.Select = "标题升序";
                messagediary = messagediary.OrderBy(a => a.Title);
            }

            else if (value == 2)
            {
                ViewBag.Select = "标题降序";
                messagediary = messagediary.OrderByDescending(a => a.Title);
            }
            else if (value == 3)
            {
                ViewBag.Select = "时间升序";
                messagediary = messagediary.OrderBy(a => a.CreateTime);
            }
            else if (value == 4)
            {
                ViewBag.Select = "时间降序";
                messagediary = messagediary.OrderByDescending(a => a.CreateTime);
            }
            else
            {
                messagediary = messagediary.OrderBy(a => a.Title);
            }
            if (!string.IsNullOrEmpty(searchInfo))
            {
                messagediary = messagediary.Where(d => d.User.UserName.Contains(searchInfo));
            }
            var model = messagediary.
            TakePage(out count, out pageCount, page, pageSize).ToList().Select(p => new UserDiaryModel
            {
                UserDiaryId = p.DiaryId,
                Content = p.Content,
                CreateTime = p.CreateTime,
                DiaryCount = p.UserId,
                Title = p.Title,
                UserName = p.User.UserName,
                UserId = p.UserId
            });
            if (page > pageCount || page < 1)
            {
                if (pageCount != 0)
                    throw new Tgnet.Exception("页码超出范围");
            }
            userDiaryModels = new PageModel<UserDiaryModel>(model, page, pageCount);
            ViewBag.page = page;
            return View(userDiaryModels);
        }

        // GET: Default/Details/5
        //展示日志内容详情
        //[AllowHtml]
        //[ValidateInput]
        public ActionResult Details(int diaryid)
        {
            var messagediary = _DiaryManager.GetDiaryService(diaryid);
            UserDiaryModel userdiarymodel = new UserDiaryModel
            {
                Content = messagediary.Content,
                CreateTime = messagediary.CreateTime,
                Title = messagediary.Title,
                UserName = messagediary.UserName
            };
            return View(userdiarymodel);
        }

        // GET: Default/Create

        public ActionResult Create()
        {
            //if (User == null)
            //    throw new Tgnet.Api.ExceptionWithErrorCode(Tgnet.Api.ErrorCode.未登录);
            return View();
        }

        // POST: Default/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "Content,Title,IsPrivate")]UserDiaryModel userdiarymodel)
        {
            //if (User == null)
            //    throw new Tgnet.Api.ExceptionWithErrorCode(Tgnet.Api.ErrorCode.未登录);

            //Diary.Data.Diary diary = new Diary.Data.Diary { Content = userdiarymodel.Content,
            //    CreateTime = DateTime.Now,
            //    Title = userdiarymodel.Title,
            //    UserId =(int) User.ID, 
            //    IsDel = false,
            //    IsPrivate = !userdiarymodel.IsPrivate };


            var DiaryService = _DiaryManager.Add((int)User.ID, userdiarymodel.Title,
                !userdiarymodel.IsPrivate, userdiarymodel.Content);
            //return JsonString(new BaseReponseModel { Msg = "创建成功", Status = "ok",
            //    Url = Url.RouteUrl(new { controller = "Diary", action = "UserIndex",
            //        userid = diary.UserId
            //    }) });
            return RedirectToAction("UserIndex", new { userid = DiaryService.UserId });
        }

        // GET: Default/Edit/5
        public ActionResult Edit(int diaryid)
        {

            var messagediary = _DiaryManager.GetDiaryService(diaryid);

            UserDiaryModel userdiarymodel = new UserDiaryModel
            {
                Content = messagediary.Content,
                CreateTime = messagediary.CreateTime,
                Title = messagediary.Title,
                UserName = messagediary.UserName,
                UserDiaryId = diaryid,
                UserId = (int)User.ID
            };
            return View(userdiarymodel);

        }

        // POST: Default/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Content,Title,UserDiaryId,IsPrivate,UserId")]UserDiaryModel userdiarymodel)
        {
            //1.调用GetDiaryService方法
            var messagediary = _DiaryManager.GetUserDiaryService(userdiarymodel.UserDiaryId, (int)User.ID);
            //2.调用updateDiary方法
            //messagediary.UpdateDiary(userdiarymodel.UserDiaryId,userdiarymodel.UserId, userdiarymodel.Content,userdiarymodel.Title);
            messagediary.Update(userdiarymodel.Content, userdiarymodel.Title, userdiarymodel.IsPrivate);
            return JsonString(new BaseReponseModel
            {
                Msg = "修改成功",
                Status = "ok",
                Url = Url.RouteUrl(new
                {
                    controller = "Diary",
                    action = "UserIndex",
                    userid = User.ID
                })
            });
        }
        // GET: Default/Delete/5
        public ActionResult Delete(int diaryid)
        {


            var messagediary = _DiaryManager.GetUserDiaryService(diaryid, (int)User.ID);
            messagediary.DeleteDiary();
            //int   PamUserId = messagediary.UserId;
            return RedirectToAction("UserIndex", new
            {
                userid = User.ID
            });
        }

        public ActionResult Publish(int diaryid)
        {
            var messagediary = _DiaryManager.GetUserDiaryService(diaryid, (int)User.ID);
            messagediary.Publish();
            return RedirectToAction("UserIndex", new
            {
                userid = User.ID
            });
        }

    }
    }

PersonalDiary/Views/Diary/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<script>
    $(function () {
        $("#creatediary").click(function () {
            var a = $("#agree_input").val();
            alter(a);
            var isPrivate = true;
            if (a != 1)
                isPrivate = false;
            //$.post("/Diary/Create", { "title": $("#input_Title").val(), "content": $("#textarea_Content").val(), "IsPrivate": isPrivate.val() }, function (obj) {
            //    if (obj) {
            //        alert(obj.Msg);
            //        window.location.href = obj.Url;
            //    }
            //}, "json");
        });
    });
</script>

<h2>Create</h2>
<div>

    <form action="/Diary/Create" method="post">
        @*<p><input name="Title" id="input_Title" /></p>
        <textarea name="Content" id="textarea_Content" placeholder="请输入日志内容，不少于5个字" maxlength="800" onforminput="3" cols=40 rows=10 style="overflow:auto"
                  text-align:center background-color:BFCEDC></textarea>
        </br>
        <input type="submit" value="保存" id="creatediary" />
        <input name="IsPrivate" id="agree_input" type="checkbox" style="margin-left:100px;display:inline-block;" value="1" />*@
        <table>
            <tr>
                <td style="text-align:center;vertical-align:middle;" >标题</td>
                <td><input name="Title" id="input_Title" /></td>
            </tr>
            <tr>
                <td style="text-align:center;vertical-align:middle;" >内容</td>
                <td>
                    <textarea name="Content" id="textarea_Content" placeholder="请输入日志内容，不少于5个字" maxlength="800" onforminput="3" cols=40 rows=10 style="overflow:auto"
                              text-align:center background-color:BFCEDC></textarea>
                </td>
            </tr>
            <tr>
                
                <td>
                  
                    <div style="float:left">
                        <input name="IsPrivate" id="agree_input" type="checkbox" style="display:inline-block;" value="true"/>发布
                    </div>
                    
                </td>
                <td>
                <div style="float:right">
    <input type="submit" value="保存" id="creatediary" />
</div>
                </td>
               
            </tr>
        </table>
    </form>
</div>

PersonalDiary/Views/Diary/Details.cshtml
@model PersonalDiary.Models.UserDiaryModel
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<table>
    <tr>
        <th>@Html.DisplayFor(m=>m.Title)</th>
    </tr>
    <tr>
        <th>@Html.DisplayFor(m=>m.CreateTime)</th>
    </tr>
    <tr>
        <th>@Html.DisplayFor(m=>m.UserName)</th>
    </tr>
    <tr>
        <th>@Html.DisplayFor(m=>m.Content)</th>
    </tr>
</table>

PersonalDiary/Views/Diary/Edit.cshtml
@model PersonalDiary.Models.UserDiaryModel
@using Tgnet.Web.Sessions;
@{
    ViewBag.Title = "Create";
}
<script src="~/Content/jq/jquery-1.11.1.js"></script>
<script>
    $(function () {
        $("#creatediary").click(function () {
            //var title = $("#Content").val();
            //alert(title);
            $.post("/Diary/Edit", { "Title": $("#title").val(), "Content": $("#Content").val(), "UserDiaryId": $("#UserDiaryId").val(), "IsPrivate": $("#agree_input").val(), "UserId": $("#UserId").val()}, function (obj) {
                //if (obj) {
                    //alert(json.Url);
                    alert(obj.Msg);
                    window.location.href = obj.Url;
                //}
            }, "json");
        });
    });
</script>


@*<script>
    $(function () {
        $("form").submit(function () {
            $.post("/Diary/Edit", { }, function (obj) {
                if (obj) {
                    alert(json.Msg);
                    window.location.href = json.Url;
                }
            }, "json");
        });
    });
</script>*@

<div>
    <h2>Edit</h2>
<form >


   <table>
       <tr>
           <td>
           <input id="UserDiaryId" type="hidden" value="@Model.UserDiaryId">
           </td>
       </tr>
       <tr>
       <td>
           <input id="UserId" type="hidden" value="@Model.UserId">
       </td>
       </tr>
       <tr>
           <td style="text-align:center;vertical-align:middle;">标题</td>
           
           <td><input name="Title"  id="title" value="@Model.Title" /></td>
       </tr>
       <tr>
           <td style="text-align:center;vertical-align:middle;" >内容</td>
           <td>
               <textarea name="Content"  placeholder="请输入日志内容，不少于5个字" maxlength="800" onforminput="3" cols=40 rows=10 style="overflow:auto"
                              text-align:center background-color:BFCEDC id="Content">@Model.Content</textarea>
           </td>
       </tr>
       <tr>
           <td>
               <div style="float:left">
                   <input name="IsPrivate" id="agree_input" type="checkbox" style="display:inline-block;" value="true" />发布
               </div>
               <div style="float:right">
                   <input type="button" value="修改" id="creatediary" class="btn btn-default" />
               </div>
            
           </td>
        
       </tr>
   </table>

    

</form>      
</div>

PersonalDiary/Views/Diary/Index.cshtml
@using Tgnet.Web.Sessions;
@model PageModel<UserDiaryModel>
@using Tgnet.Web.Mvc;
@using Tgnet.Web.Sessions;
@using PersonalDiary.Models;
@{
    ViewBag.Title = "Index";
}
@Html.ActionLink("Create", "Create")
<h2>Index</h2>
@using{ 

}
<form action="" method="get">
    <label>关键字</label>
    <select name="">
        <option value="0"></option>
        <option value="1"></option>
    </select>
</form>
<table>
    <tr>
        <td>Title</td>
        <td>Content</td>
        <td>UserName</td>
        <td>CreateTime</td>
    </tr>
</table>
@{
    foreach (var item in Model)
    {
        <table>
            <tr>
                <td>
                    @item.Title
                </td>
                <td>
                    @item.Content
                </td>
                <td>
                    @item.UserName
                </td>
                <td>
                    @item.CreateTime
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { diaryid = item.UserDiaryId }) |
                    @Html.ActionLink("Details", "Details", new { diaryid = item.UserDiaryId }) |
                    @Html.ActionLink("Delete", "Delete", new { diaryid = item.UserDiaryId })
                </td>
            </tr>

        </table>

    }
    <p>@ViewBag.User</p>
}

PersonalDiary/Views/Diary/UserIndex.cshtml
@using Tgnet.Web.Sessions;
@model PageModel<UserDiaryModel>
@using Tgnet.Web.Mvc;
@using Tgnet.Web.Sessions;
@using PersonalDiary.Models;
@{
    ViewBag.Title = "Index";
    ViewBag.OptionValue = 1;
}
@*1*@
<script src="~/Content/jq/jquery-1.11.1.js"></script>
<script>
    $(function () {
        $("#Input_Filter").click(function () {
            var optionValue = $("#sort option:selected").val();
            var searchInfo = $("#Input_Search").val();
            alert(searchInfo);
            window.location.href = "/Diary/UserIndex?value=" + optionValue + "&page=" + "&searchInfo=" + searchInfo;
            @*if (@ViewBag.userid== 0)
                { window.location.href = "/Diary/UserIndex?value=" + optionValue + "&searchInfo=" + searchInfo; }
                else
                { window.location.href = "/Diary/UserIndex?userid=" +@ViewBag.userid+"&value=" + optionValue + "&searchInfo=" + searchInfo; }*@
        });
        $("#next_input").click(function (e) {

            var a = $("#next_input").val()
            var page =@ViewBag.page +1;
            if (page > @Model.PageCount)
            {
            return false;
            }

            //用户登录
            if (@ViewBag.userid != 0)
            {
                window.location.href="/Diary/UserIndex?userid=@ViewBag.userid&value=@ViewBag.Select&page="+page+"&searchInfo=@ViewBag.searchInfo";
                @*window.location.href = "/Diary/UserIndex?userid=" + @ViewBag.userid + "&page=" + page;*@
            }
                //未有用户登录的
            else {window.location.href = "/Diary/UserIndex?value=@ViewBag.Select&page="+page+"&searchInfo=@ViewBag.searchInfo" ; }
        } );
        $("#front_input").click(function (e) {
            var a = $("#front_input").val()
            var b=@ViewBag.userid;

            var page =@ViewBag.page -1;
            if (page < 1) {
                return false;
            }
            if (@ViewBag.userid != 0) { window.location.href = window.location.href="/Diary/UserIndex?userid=@ViewBag.userid&value=@ViewBag.Select&page="+page+"&searchInfo=@ViewBag.searchInfo"; }
            else {
                window.location.href = "/Diary/UserIndex?value=@ViewBag.Select&page="+page+"&searchInfo=@ViewBag.searchInfo";
        }
        });
        $("#first_page").click(function (e) {
            var a = $("#first_page").val()
            var b=@ViewBag.userid;
            var page =1;
            if (@ViewBag.userid != 0) { window.location.href = "/Diary/UserIndex?userid=@ViewBag.userid&value=@ViewBag.Select&page="+page+"&searchInfo=@ViewBag.searchInfo"; }
            else {
                window.location.href = "/Diary/UserIndex?value=@ViewBag.Select&page="+page+"&searchInfo=@ViewBag.searchInfo";
        }
        });
                $("#last_page").click(function (e) {
            var a = $("#last_page").val()
            var b=@ViewBag.userid;
            var page =@Model.PageCount;
                    if (@ViewBag.userid != 0) { window.location.href ="/Diary/UserIndex?userid=@ViewBag.userid&value=@ViewBag.Select&page="+page+"&searchInfo=@ViewBag.searchInfo"; }
            else {
                window.location.href = "/Diary/UserIndex?value=@ViewBag.Select&page="+page+"&searchInfo=@ViewBag.searchInfo";
        }
                });
    // 分布页
        @*$("#sort").change(function () {
            var a = $("#sort option:selected").val();
            var searchInfo = $("#Input_Search").val();
            var b =@ViewBag.userid;
             var page =@ViewBag.page;
            $.ajax({
                type: "GET",
                dataType: "html",
                     url: "/Diary/Sort",
                     data: "value=" + a +  "&page=" + page+ "&searchInfo=" + searchInfo ,
                    beforeSend: function (XMLHttpRequest) {
                    $("#test_ajax").text("正在查询...");
                    // Pause(this,100000);
                },
                success: function (html) {
                    $("#test_ajax").html(html);
                    $("#test_ajax").css("color", "red");
                },
                complete: function (XMLHttpRequest, textStatus) {
                    //隐藏正在查询图片
                },
                error: function () {
                    $("#test_ajax").text("出错了...");
                }
            });
        } );*@
    });
    </script>

@*2*@
@Html.ActionLink("Create", "Create")

<h2>Index</h2>
<h2>@ViewBag.User</h2>
@*@using{

    }*@
<p>
  @if (ViewBag.userid == 0)
  {  <a href="/User/Login">Login</a> }
  
  @if (ViewBag.userid != 0)
  {  <a href="/User/LogOut">LogOut</a>}
   
</p>

@*<form action="" method="post">*@



    @*@using (Ajax.BeginForm(new AjaxOptions
        {
            HttpMethod = "get",                    //使用get方法请求
            InsertionMode = InsertionMode.Replace, //将过滤的数据覆盖原数据
            UpdateTargetId = "user_diary_List"          //覆盖的地方(值为标签ID)
        }))
        {
            <input type="search" name="searchString" />
            <input type="submit" name="Filter" />
        }
        @Html.Partial("_IndexPartialPage", Model)               @*/*引用分部视图，第一个值
        为分部视图名，第二个值是
        把model传过去*/*@
<label >关键字</label>
    <input id="Input_Search" placeholder="输入姓名搜索...." type="search" name="searchstring" />
    <select name="sort" id="sort">
        <option selected>@ViewBag.Select</option>
        <option value="1">标题升序</option>
        <option value="2">标题降序</option>
        <option value="3">时间升序</option>
        <option value="4">时间降序</option>
    </select>
<input id="Input_Filter" type="submit" name="Filter" />
@*</form>*@


    <div id="test_ajax">
        <table>
            @{
                <tr>
                    <td>Title</td>
                    <td>Content</td>
                    <td>UserName</td>
                    <td>CreateTime</td>
                </tr>
                foreach (var item in Model)
                {

                    <tr>
                        <td>
                            @item.Title
                        </td>
                        <td>
                            <a href="@Url.Action("Details", "Diary",new { diaryid = item.UserDiaryId })">
                                @item.Content.Substring(0, 1)
                            </a>

                        </td>
                        <td>
                            @item.UserName.Substring(0, 3)
                        </td>
                        <td>
                            @item.CreateTime.ToString().Substring(0,13)
                        </td>
                        @*有用户登陆*@
                        @if (ViewBag.userid != 0)
                        {
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { diaryid = item.UserDiaryId }) |
                                @Html.ActionLink("Details", "Details", new { diaryid = item.UserDiaryId }) |
                                @Html.ActionLink("Delete", "Delete", new { diaryid = item.UserDiaryId })|
                                @Html.ActionLink("Publish", "Publish", new { diaryid = item.UserDiaryId })|
                            </td>
                            <td>
                                <a href="@Url.Action("Index", "DiaryComment", new RouteValueDictionary { { "diaryid", item.UserDiaryId } })">Read|</a>
                                <a href="@Url.Action("Add", "DiaryComment",new { diaryid = item.UserDiaryId })">Add</a>
                            </td>
                        }
                        else
                        {
                            <td>
                                @Html.ActionLink("Details", "Details", new { diaryid = item.UserDiaryId }) |
                            </td>
                            <td>
                                <a href="@Url.Action("Index", "DiaryComment", new RouteValueDictionary { { "diaryid", item.UserDiaryId } })">Read</a>|
                                <a href="@Url.Action("Add", "DiaryComment",new { diaryid = item.UserDiaryId })">Add</a>
                            </td>
                        }
                        @*未有用户登陆*@

                    </tr>
                }

                <p>@ViewBag.User</p>

            }
        </table>  
        <input type="button" id="first_page" value="first" />
        <input type="button" id="front_input" value="front" />
        <input type="button" id="next_input" value="next" />
        <input type="button" id="last_page" value="last" />
    </div>

PersonalDiary/Views/Diary/_Sort.cshtml
@using Tgnet.Web.Sessions;
@model PageModel<UserDiaryModel>
@using Tgnet.Web.Mvc;
@using Tgnet.Web.Sessions;
@using PersonalDiary.Models;
@{
    ViewBag.Title = "Index";
    ViewBag.OptionValue = 1;
}
<div id="test_ajax">
    <table>
        @{
            <tr>
                <td>Title</td>
                <td>Content</td>
                <td>UserName</td>
                <td>CreateTime</td>
            </tr>
            foreach (var item in Model)
            {

                <tr>
                    <td>
                        @item.Title
                    </td>
                    <td>
                        <a href="@Url.Action("Details", "Diary",new { diaryid = item.UserDiaryId })">
                            @item.Content.Substring(0, 1)
                        </a>

                    </td>
                    <td>
                        @item.UserName.Substring(0, 3)
                    </td>
                    <td>
                        @item.CreateTime
                    </td>
                    @*有用户登陆*@
                    @if (ViewBag.userid != 0)
                    {
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { diaryid = item.UserDiaryId }) |
                            @Html.ActionLink("Details", "Details", new { diaryid = item.UserDiaryId }) |
                            @Html.ActionLink("Delete", "Delete", new { diaryid = item.UserDiaryId })|
                            @Html.ActionLink("Publish", "Publish", new { diaryid = item.UserDiaryId })|
                        </td>
                        <td>
                            <a href="@Url.Action("Index", "DiaryComment", new RouteValueDictionary { { "diaryid", item.UserDiaryId } })">Read|</a>
                            <a href="@Url.Action("Add", "DiaryComment",new { diaryid = item.UserDiaryId })">Add</a>
                        </td>
                    }
                    else
                    {
                        <td>
                            @Html.ActionLink("Details", "Details", new { diaryid = item.UserDiaryId }) |
                        </td>
                        <td>
                            <a href="@Url.Action("Index", "DiaryComment", new RouteValueDictionary { { "diaryid", item.UserDiaryId } })">Read</a>|
                            <a href="@Url.Action("Add", "DiaryComment",new { diaryid = item.UserDiaryId })">Add</a>
                        </td>
                    }
                    @*未有用户登陆*@

                </tr>
            }

            <p>@ViewBag.User</p>

        }
    </table>
    <input type="button" id="first_page" value="first" />
    <input type="button" id="front_input" value="front" />
    <input type="button" id="next_input" value="next" />
    <input type="button" id="last_page" value="last" />
</div>